FROM golang:1.26-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o migrate ./cmd/migrate/

FROM alpine:3.21
WORKDIR /app
COPY --from=builder /build/migrate .
COPY db/migrations ./db/migrations
CMD ["/app/migrate"]
