// Package entity holds the GORM models that define the database schema.
//
// The schema used to live in backend/db/migrations/*.sql (golang-migrate) and drifted away from the SQL
// the services actually issued. It is now owned by these structs and applied with AutoMigrate at
// startup, so the columns, indexes and constraints can never disagree with the Go types again.
//
// Naming: GORM's default naming strategy maps Link -> links, ClickLog -> click_logs and so on, so the
// existing table and column names are preserved and no data migration is required. Where the default
// would be wrong (the link_tags junction table) TableName() is overridden.
package entity

import (
	"time"

	"gorm.io/gorm"
)

// Link is a short link.
type Link struct {
	ID           int64      `gorm:"primaryKey" json:"id"`
	ShortCode    string     `gorm:"type:varchar(20);uniqueIndex;not null" json:"short_code"`
	OriginalURL  string     `gorm:"type:text;not null" json:"original_url"`
	Title        *string    `gorm:"type:varchar(500)" json:"title"`
	Description  *string    `gorm:"type:text" json:"description"`
	ImageURL     *string    `gorm:"type:text" json:"image_url"`
	Domain       string     `gorm:"type:varchar(255);default:kada.link" json:"domain"`
	PasswordHash *string    `gorm:"type:varchar(255)" json:"password_hash,omitempty"`
	ExpiresAt    *time.Time `json:"expires_at"`
	IsActive     bool       `gorm:"default:true" json:"is_active"`
	ClickCount   int64      `gorm:"default:0" json:"click_count"`
	// ON DELETE SET NULL: deleting an account must not delete the links that were created with it.
	UserID      *int64 `gorm:"index" json:"user_id"`
	WorkspaceID *int64 `gorm:"index" json:"workspace_id"`
	FolderID    *int64 `gorm:"index" json:"folder_id"`

	UTMSource   *string `gorm:"type:varchar(255)" json:"utm_source"`
	UTMMedium   *string `gorm:"type:varchar(255)" json:"utm_medium"`
	UTMCampaign *string `gorm:"type:varchar(255)" json:"utm_campaign"`
	UTMTerm     *string `gorm:"type:varchar(255)" json:"utm_term"`
	UTMContent  *string `gorm:"type:varchar(255)" json:"utm_content"`
	IosURL      *string `gorm:"type:text" json:"ios_url"`
	AndroidURL  *string `gorm:"type:text" json:"android_url"`

	CreatedAt time.Time `gorm:"index" json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	// Associations. Constraints are declared with OnDelete so AutoMigrate reproduces the behavior of the
	// original SQL: a deleted folder/workspace must detach its links, not delete them.
	User      *User      `gorm:"foreignKey:UserID;constraint:OnDelete:SET NULL" json:"-"`
	Folder    *Folder    `gorm:"foreignKey:FolderID;constraint:OnDelete:SET NULL" json:"-"`
	Workspace *Workspace `gorm:"foreignKey:WorkspaceID;constraint:OnDelete:SET NULL" json:"-"`
}

// ClickLog is one recorded click on a short link.
type ClickLog struct {
	ID int64 `gorm:"primaryKey" json:"id"`
	// ON DELETE CASCADE is declared on the association below (and nowhere else): a constraint tag on both
	// the field and the association would make AutoMigrate try to create two different foreign keys.
	LinkID    *int64    `gorm:"index" json:"link_id"`
	IP        *string   `gorm:"type:varchar(45)" json:"ip"`
	UserAgent *string   `gorm:"type:text" json:"user_agent"`
	Platform  *string   `gorm:"type:click_platform;default:unknown;index" json:"platform"`
	Referer   *string   `gorm:"type:text" json:"referer"`
	Country   *string   `gorm:"type:varchar(10)" json:"country"`
	Province  *string   `gorm:"type:varchar(50)" json:"province"`
	City      *string   `gorm:"type:varchar(50)" json:"city"`
	CreatedAt time.Time `gorm:"index" json:"created_at"`
	// EventID is the idempotency key generated by the producer: the unique index makes Kafka redelivery
	// (at-least-once) hit ON CONFLICT DO NOTHING instead of counting the same click twice.
	EventID *string `gorm:"type:varchar(64);uniqueIndex" json:"event_id"`

	Link *Link `gorm:"foreignKey:LinkID;constraint:OnDelete:CASCADE" json:"-"`
}

// SMSVerificationCode is a pending SMS login code.
//
// Nothing is read back through this model yet (auth_service issues raw SQL for the atomic
// consume/attempt statements), but it is the schema definition for the table.
type SMSVerificationCode struct {
	ID    int64  `gorm:"primaryKey" json:"id"`
	Phone string `gorm:"type:varchar(20);not null;index:idx_sms_codes_phone,priority:1" json:"phone"`
	// CodeHash stores sha256(code); the plaintext code is never persisted.
	CodeHash  *string   `gorm:"type:varchar(64);index" json:"code_hash"`
	IP        *string   `gorm:"type:varchar(45)" json:"ip"`
	Used      bool      `gorm:"default:false" json:"used"`
	Attempts  int       `gorm:"not null;default:0" json:"attempts"`
	ExpiresAt time.Time `gorm:"not null" json:"expires_at"`
	CreatedAt time.Time `gorm:"index:idx_sms_codes_phone,priority:2" json:"created_at"`
}

// TableName pins the table name: GORM's pluralizer would produce "sms_verification_codes", but the table
// has been called sms_codes since the first migration and auth_service still writes it with raw SQL.
func (SMSVerificationCode) TableName() string { return "sms_codes" }

// User is an account. A single user may authenticate by phone, email or WeChat.
//
// The WeChat column names are declared explicitly because GORM shortens acronyms mid-name:
// WechatOpenID would map to wechat_open_id, while the column is wechat_openid.
type User struct {
	ID            int64      `gorm:"primaryKey" json:"id"`
	Phone         *string    `gorm:"type:varchar(20);uniqueIndex;index" json:"phone"`
	Email         *string    `gorm:"type:varchar(255);uniqueIndex;index" json:"email"`
	WechatOpenID  *string    `gorm:"column:wechat_openid;type:varchar(128);uniqueIndex;index" json:"wechat_openid"`
	WechatUnionID *string    `gorm:"column:wechat_unionid;type:varchar(128)" json:"wechat_unionid"`
	Name          *string    `gorm:"type:varchar(100)" json:"name"`
	Avatar        *string    `gorm:"type:text" json:"avatar"`
	PasswordHash  *string    `gorm:"type:varchar(255)" json:"-"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	LastLoginAt   *time.Time `json:"last_login_at"`
	LastLoginIP   *string    `gorm:"type:varchar(45)" json:"last_login_ip"`
}

// Folder groups a user's links.
type Folder struct {
	ID        int64     `gorm:"primaryKey" json:"id"`
	UserID    int64     `gorm:"not null;index" json:"user_id"`
	Name      string    `gorm:"type:varchar(100);not null" json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	User *User `gorm:"foreignKey:UserID;constraint:OnDelete:CASCADE" json:"-"`
}

// Tag labels links, many-to-many through link_tags.
type Tag struct {
	ID        int64     `gorm:"primaryKey" json:"id"`
	UserID    int64     `gorm:"not null;index" json:"user_id"`
	Name      string    `gorm:"type:varchar(50);not null" json:"name"`
	Color     string    `gorm:"type:varchar(7);default:#6366F1" json:"color"`
	CreatedAt time.Time `json:"created_at"`

	User *User `gorm:"foreignKey:UserID;constraint:OnDelete:CASCADE" json:"-"`
}

// LinkTag is the link <-> tag junction table.
type LinkTag struct {
	LinkID int64 `gorm:"primaryKey" json:"link_id"`
	TagID  int64 `gorm:"primaryKey" json:"tag_id"`

	Link *Link `gorm:"foreignKey:LinkID;constraint:OnDelete:CASCADE" json:"-"`
	Tag  *Tag  `gorm:"foreignKey:TagID;constraint:OnDelete:CASCADE" json:"-"`
}

func (LinkTag) TableName() string { return "link_tags" }

// Domain is a custom domain a user wants to serve short links from.
type Domain struct {
	ID         int64      `gorm:"primaryKey" json:"id"`
	UserID     int64      `gorm:"not null;index;uniqueIndex:idx_domains_user_name,priority:1" json:"user_id"`
	Name       string     `gorm:"type:varchar(255);not null;uniqueIndex:idx_domains_user_name,priority:2" json:"name"`
	Verified   bool       `gorm:"default:false" json:"verified"`
	VerifiedAt *time.Time `json:"verified_at"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`

	User *User `gorm:"foreignKey:UserID;constraint:OnDelete:CASCADE" json:"-"`
}

// UTMTemplate is a reusable set of UTM parameters.
type UTMTemplate struct {
	ID          int64     `gorm:"primaryKey" json:"id"`
	UserID      int64     `gorm:"not null;index" json:"user_id"`
	Name        string    `gorm:"type:varchar(255);not null" json:"name"`
	UTMSource   *string   `gorm:"type:varchar(255)" json:"utm_source"`
	UTMMedium   *string   `gorm:"type:varchar(255)" json:"utm_medium"`
	UTMCampaign *string   `gorm:"type:varchar(255)" json:"utm_campaign"`
	UTMTerm     *string   `gorm:"type:varchar(255)" json:"utm_term"`
	UTMContent  *string   `gorm:"type:varchar(255)" json:"utm_content"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`

	User *User `gorm:"foreignKey:UserID;constraint:OnDelete:CASCADE" json:"-"`
}

// APIToken is a long-lived bearer token for programmatic access. Only its sha256 hash is stored.
type APIToken struct {
	ID        int64      `gorm:"primaryKey" json:"id"`
	UserID    int64      `gorm:"not null;index" json:"user_id"`
	Name      string     `gorm:"type:varchar(100);not null" json:"name"`
	TokenHash string     `gorm:"type:varchar(64);not null;uniqueIndex;index" json:"-"`
	LastUsed  *time.Time `json:"last_used"`
	CreatedAt time.Time  `json:"created_at"`

	User *User `gorm:"foreignKey:UserID;constraint:OnDelete:CASCADE" json:"-"`
}

// Workspace scopes links to a team/project.
type Workspace struct {
	ID        int64     `gorm:"primaryKey" json:"id"`
	Name      string    `gorm:"type:varchar(100);not null" json:"name"`
	Slug      string    `gorm:"type:varchar(50);not null;uniqueIndex" json:"slug"`
	UserID    int64     `gorm:"not null;index" json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	// Workspaces have no ON DELETE clause in the original schema, so deleting a user is rejected while
	// links still reference the workspace. Keep the default (NO ACTION) behavior.
	User *User `gorm:"foreignKey:UserID" json:"-"`
}

// Models returns every entity in a stable, dependency-first order.
//
// The order matters for AutoMigrate: PostgreSQL cannot add a foreign key to a table that does not exist
// yet, so referenced tables must be created before the tables that point at them.
func Models() []any {
	return []any{
		&User{},
		&Workspace{},
		&Folder{},
		&Tag{},
		&Link{},
		&LinkTag{},
		&ClickLog{},
		&SMSVerificationCode{},
		&Domain{},
		&UTMTemplate{},
		&APIToken{},
	}
}

// BeforeCreate applies the column defaults that the original SQL migrations declared with DEFAULT.
//
// GORM only fills defaults from a database round-trip when a field is left at its zero value and the tag
// has no explicit value, and `default:true` / `default:false` on a Go bool would rewrite an intentional
// false to true (or the other way round). Setting them explicitly keeps the values the services pass in.
func (l *Link) BeforeCreate(*gorm.DB) error {
	if l.Domain == "" {
		l.Domain = "kada.link"
	}
	return nil
}

func (t *Tag) BeforeCreate(*gorm.DB) error {
	if t.Color == "" {
		t.Color = "#6366F1"
	}
	return nil
}
